name: 'build image and push to ghcr.io'

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
    - name: "checkout"
      uses: actions/checkout@v3
    - name: "build container image"
      run: |
        docker build . --file ./Dockerfile --tag ghcr.io/senbazuru/docker-go-ffmpeg-aws:latest
        docker tag ghcr.io/senbazuru/docker-go-ffmpeg-aws:latest ghcr.io/senbazuru/docker-go-ffmpeg-aws:${{ github.sha }}
    - name: "login to ghcr.io"
      run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u USERNAME --password-stdin
    - name: "push container image to ghcr.io"
      run: docker push ghcr.io/senbazuru/docker-go-ffmpeg-aws:latest
